// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    RISCZERO_FIBONACCI_ELF, RISCZERO_FIBONACCI_ID
};
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {

    // Execute the guest code.
    let env = ExecutorEnv::builder().write(&iterations).unwrap().build().unwrap();
    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove_elf(env, RISCZERO_FIBONACCI_ELF).unwrap();

    let proof = bincode::serialize(&receipt).unwrap();
    println!("{}",proof.len());
    // Optional: Verify receipt to confirm that recipients will also be able to
    // verify your receipt
    receipt.verify(RISCZERO_FIBONACCI_ID).unwrap();
}
