[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.0", default-features = false }
serde = "1.0"

[features]
metal = ["risc0-zkvm/metal"]