[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1"}
serde = "1.0"
bincode = "1.3.3"

[features]
default = []
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
profiler = ["risc0-zkvm/profiler"]
